# Clustering Experiment Configuration

# Dataset configuration
dataset:
  name: "AI-Secure/PolyGuard"
  subset: "cyber"
  split: null
  num_samples: null  # Use all samples if null

# Model configuration
model:
  name: "Qwen/Qwen3-Embedding-8B"
  device: "auto"  # auto, cpu, cuda, mps
  save_embeddings: "PolyGuard_cyber_embeddings.pt"  # Path to save embeddings tensor

# HDBSCAN clustering configuration
clustering:
  min_cluster_size: 3
  metric: "cosine"  # cosine, euclidean, manhattan
  leaf_size: 40
  min_samples: null  # Uses min_cluster_size if null

# Output configuration
output:
  path: "PolyGuard_cyber_clusters.json"  # Output directory or full path
  indent: 2  # JSON indentation
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR