# Clustering Experiment Configuration

# Dataset configuration
dataset:
  name: "PKU-Alignment/BeaverTails"
  subset: null
  split: "330k_train"
  num_samples: null  # Use all samples if null
  save_queries: "BeaverTails_queries.json"  # Path to save filtered queries

# Model configuration
model:
  name: "Qwen/Qwen3-Embedding-8B"
  domain: "general"
  device: "auto"  # auto, cpu, cuda, mps
  save_embeddings: "BeaverTails_embeddings.pt"  # Path to save embeddings tensor

# HDBSCAN clustering configuration
clustering:
  min_cluster_size: 5
  metric: "cosine"  # cosine, euclidean, manhattan
  leaf_size: 40
  min_samples: null  # Uses min_cluster_size if null

# Output configuration
output:
  path: "BeaverTails_clusters.json"  # Output directory or full path
  indent: 2  # JSON indentation
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR