# Clustering Experiment Configuration

# Dataset configuration
dataset:
  name: "AI-Secure/PolyGuard"
  subset: "education"
  split: null
  mutate: true

# Model configuration
model:
  name: "Qwen/Qwen3-Embedding-8B"
  domain: "education"
  device: "auto"  # auto, cpu, cuda, mps

# HDBSCAN clustering configuration
clustering:
  min_cluster_size: 3
  metric: "cosine"  # cosine, euclidean, manhattan
  leaf_size: 40
  min_samples: null  # Uses min_cluster_size if null

# Output configuration
output:
  dir_name: "PolyGuard_education_mutate"
  log_level: "INFO"  # DEBUG, INFO, WARNING, ERROR